-- MySQL Script generated by MySQL Workbench
-- 11/16/16 14:26:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema moviePlanet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema moviePlanet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moviePlanet` DEFAULT CHARACTER SET utf8 ;
USE `moviePlanet` ;

-- -----------------------------------------------------
-- Table `moviePlanet`.`filmingTime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviePlanet`.`filmingTime` (
  `filmingTimeID` INT NOT NULL,
  `year` INT NULL,
  `month` INT NULL,
  `day` INT NULL,
  PRIMARY KEY (`filmingTimeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviePlanet`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviePlanet`.`User` (
  `userID` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviePlanet`.`Rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviePlanet`.`Rating` (
  `ratingID` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`ratingID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviePlanet`.`screeningTime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviePlanet`.`screeningTime` (
  `screeningTimeID` INT NOT NULL,
  `hour` INT NULL,
  `minute` INT NULL,
  `second` INT NULL,
  PRIMARY KEY (`screeningTimeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviePlanet`.`Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviePlanet`.`Movie` (
  `movieID` INT NOT NULL,
  `filmingTimeID` INT NOT NULL,
  `screeningTimeID` INT NOT NULL,
  `userID` INT NOT NULL,
  `ratingID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `score` VARCHAR(45) NULL,
  PRIMARY KEY (`movieID`),
  INDEX `fk_Movie_Time_idx` (`filmingTimeID` ASC),
  INDEX `fk_Movie_User1_idx` (`userID` ASC),
  INDEX `fk_Movie_Rating1_idx` (`ratingID` ASC),
  INDEX `fk_Movie_screeningTime1_idx` (`screeningTimeID` ASC),
  CONSTRAINT `fk_Movie_Time`
    FOREIGN KEY (`filmingTimeID`)
    REFERENCES `moviePlanet`.`filmingTime` (`filmingTimeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_User1`
    FOREIGN KEY (`userID`)
    REFERENCES `moviePlanet`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_Rating1`
    FOREIGN KEY (`ratingID`)
    REFERENCES `moviePlanet`.`Rating` (`ratingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_screeningTime1`
    FOREIGN KEY (`screeningTimeID`)
    REFERENCES `moviePlanet`.`screeningTime` (`screeningTimeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviePlanet`.`Actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviePlanet`.`Actor` (
  `actorID` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `dob` DATE NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`actorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviePlanet`.`Producer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviePlanet`.`Producer` (
  `producerID` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `dob` DATE NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`producerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviePlanet`.`Director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviePlanet`.`Director` (
  `directorID` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `dob` DATE NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`directorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviePlanet`.`Awards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviePlanet`.`Awards` (
  `awardsID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`awardsID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviePlanet`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviePlanet`.`Genre` (
  `genreID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`genreID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviePlanet`.`Writer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviePlanet`.`Writer` (
  `writerID` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `dob` DATE NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`writerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviePlanet`.`Actor_has_Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviePlanet`.`Actor_has_Movie` (
  `Actor_actorID` INT NOT NULL,
  `Movie_movieID` INT NOT NULL,
  PRIMARY KEY (`Actor_actorID`, `Movie_movieID`),
  INDEX `fk_Actor_has_Movie_Movie1_idx` (`Movie_movieID` ASC),
  INDEX `fk_Actor_has_Movie_Actor1_idx` (`Actor_actorID` ASC),
  CONSTRAINT `fk_Actor_has_Movie_Actor1`
    FOREIGN KEY (`Actor_actorID`)
    REFERENCES `moviePlanet`.`Actor` (`actorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actor_has_Movie_Movie1`
    FOREIGN KEY (`Movie_movieID`)
    REFERENCES `moviePlanet`.`Movie` (`movieID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviePlanet`.`Movie_has_Awards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviePlanet`.`Movie_has_Awards` (
  `Movie_movieID` INT NOT NULL,
  `Awards_awardsID` INT NOT NULL,
  PRIMARY KEY (`Movie_movieID`, `Awards_awardsID`),
  INDEX `fk_Movie_has_Awards_Awards1_idx` (`Awards_awardsID` ASC),
  INDEX `fk_Movie_has_Awards_Movie1_idx` (`Movie_movieID` ASC),
  CONSTRAINT `fk_Movie_has_Awards_Movie1`
    FOREIGN KEY (`Movie_movieID`)
    REFERENCES `moviePlanet`.`Movie` (`movieID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_Awards_Awards1`
    FOREIGN KEY (`Awards_awardsID`)
    REFERENCES `moviePlanet`.`Awards` (`awardsID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviePlanet`.`Director_has_Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviePlanet`.`Director_has_Movie` (
  `Director_directorID` INT NOT NULL,
  `Movie_movieID` INT NOT NULL,
  PRIMARY KEY (`Director_directorID`, `Movie_movieID`),
  INDEX `fk_Director_has_Movie_Movie1_idx` (`Movie_movieID` ASC),
  INDEX `fk_Director_has_Movie_Director1_idx` (`Director_directorID` ASC),
  CONSTRAINT `fk_Director_has_Movie_Director1`
    FOREIGN KEY (`Director_directorID`)
    REFERENCES `moviePlanet`.`Director` (`directorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Director_has_Movie_Movie1`
    FOREIGN KEY (`Movie_movieID`)
    REFERENCES `moviePlanet`.`Movie` (`movieID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviePlanet`.`Movie_has_Writer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviePlanet`.`Movie_has_Writer` (
  `Movie_movieID` INT NOT NULL,
  `Writer_writerID` INT NOT NULL,
  PRIMARY KEY (`Movie_movieID`, `Writer_writerID`),
  INDEX `fk_Movie_has_Writer_Writer1_idx` (`Writer_writerID` ASC),
  INDEX `fk_Movie_has_Writer_Movie1_idx` (`Movie_movieID` ASC),
  CONSTRAINT `fk_Movie_has_Writer_Movie1`
    FOREIGN KEY (`Movie_movieID`)
    REFERENCES `moviePlanet`.`Movie` (`movieID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_Writer_Writer1`
    FOREIGN KEY (`Writer_writerID`)
    REFERENCES `moviePlanet`.`Writer` (`writerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviePlanet`.`Movie_has_Producer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviePlanet`.`Movie_has_Producer` (
  `Movie_movieID` INT NOT NULL,
  `Producer_producerID` INT NOT NULL,
  PRIMARY KEY (`Movie_movieID`, `Producer_producerID`),
  INDEX `fk_Movie_has_Producer_Producer1_idx` (`Producer_producerID` ASC),
  INDEX `fk_Movie_has_Producer_Movie1_idx` (`Movie_movieID` ASC),
  CONSTRAINT `fk_Movie_has_Producer_Movie1`
    FOREIGN KEY (`Movie_movieID`)
    REFERENCES `moviePlanet`.`Movie` (`movieID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_Producer_Producer1`
    FOREIGN KEY (`Producer_producerID`)
    REFERENCES `moviePlanet`.`Producer` (`producerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviePlanet`.`Movie_has_Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviePlanet`.`Movie_has_Genre` (
  `Movie_movieID` INT NOT NULL,
  `Genre_genreID` INT NOT NULL,
  PRIMARY KEY (`Movie_movieID`, `Genre_genreID`),
  INDEX `fk_Movie_has_Genre_Genre1_idx` (`Genre_genreID` ASC),
  INDEX `fk_Movie_has_Genre_Movie1_idx` (`Movie_movieID` ASC),
  CONSTRAINT `fk_Movie_has_Genre_Movie1`
    FOREIGN KEY (`Movie_movieID`)
    REFERENCES `moviePlanet`.`Movie` (`movieID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_Genre_Genre1`
    FOREIGN KEY (`Genre_genreID`)
    REFERENCES `moviePlanet`.`Genre` (`genreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
